# Generated by Django 5.2.8 on 2025-11-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_region_farm_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='intended_crop',
            field=models.ForeignKey(blank=True, help_text='Crop the farmer wants to plant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intended_farms', to='api.crop'),
        ),
    ]
