import { createContext, useContext, useState } from 'react'

const translations = {
    en: {
        // Common
        home: 'Home',
        login: 'Login',
        logout: 'Logout',
        welcome: 'Welcome',
        getStarted: 'Get Started',
        blockchainTracker: 'Blockchain Tracker',
        aiAnalytics: 'AI Analytics',
        backToDashboard: 'Back to Dashboard',
        selectFarm: 'Select Farm',
        noFarmsMessage: 'No farms found',
        createFarmFirst: 'Please create a farm first using the form on the left',
        region: 'Region',
        selectRegion: 'Select Region',
        selectedRegion: 'Selected Region',
        autoDetected: 'Auto-detected',
        aiAdvice: 'AI Advice',
        allCropsAdvice: 'Advice for All Crops',
        intendedCrop: 'Intended Crop',
        optional: 'Optional',
        selectIntendedCrop: 'Select Crop You Want to Plant',
        intendedCropHelp: 'Select the crop you are thinking of planting. AI will analyze it and suggest alternatives if needed.',
        yourCropAnalysis: 'Your Crop Analysis',
        recommended: 'Recommended',
        notRecommended: 'Not Recommended',
        alternatives: 'Alternative Crops',
        alternativesDescription: 'Based on your farm conditions, these crops are better alternatives:',
        reason: 'Reason',
        roi: 'ROI',
        confidence: 'Confidence Level',
        criticalAdvice: 'Critical Issues',
        warnings: 'Warnings',
        recommendations: 'Recommendations',
        opportunities: 'Opportunities',
        information: 'Information',
        action: 'Recommended Action',

        // Auth
        welcomeBack: 'Welcome Back',
        signInToAccount: 'Sign in to your AgriData account',
        emailAddress: 'Email Address',
        password: 'Password',
        signIn: 'Sign In',
        signingIn: 'Signing in...',
        dontHaveAccount: "Don't have an account?",
        signUp: 'Sign up',
        backToHome: 'Back to home',
        createAccount: 'Create Account',
        joinToday: 'Join AgriData Insight today',
        firstName: 'First Name',
        lastName: 'Last Name',
        confirmPassword: 'Confirm Password',
        creatingAccount: 'Creating account...',
        alreadyHaveAccount: 'Already have an account?',

        // Dashboard
        updateFarmDetails: 'Update Farm Details',
        farmName: 'Farm Name',
        location: 'Location',
        size: 'Size (Hectares)',
        soilType: 'Soil Type',
        updateAnalysis: 'Update Analysis',
        updating: 'Updating...',
        topRecommendation: 'Top Recommendation',
        recommendedArea: 'Recommended Area',
        expectedYield: 'Expected Yield',
        expectedRevenue: 'Expected Revenue',
        ofYourFarm: 'of your farm',
        totalHarvest: 'total harvest',
        estimatedIncome: 'estimated income',
        score: 'Score',
        currentContext: 'Current Context',
        farmId: 'Farm ID',
        analyzingData: 'Analyzing soil and market data...',
        detailedAnalysis: 'Detailed Analysis',
        crop: 'Crop',
        suitability: 'Suitability',
        yield: 'Yield',
        profit: 'Profit',
        risk: 'Risk',
        finalScore: 'Final Score',
        farmUpdatedSuccess: 'Farm updated successfully! Recommendations refreshed.',
        soilLoam: 'Loam (Balanced)',
        soilClay: 'Clay (Heavy)',
        soilSand: 'Sand (Draining)',
        soilSilt: 'Silt (Fertile)',

        // Analytics
        precisionAnalytics: 'Precision Analytics',
        realtimeFarmMonitoring: 'Real-Time Farm Monitoring',
        aiPoweredInsights: 'AI-powered insights from IoT sensors across your farm',
        soilSensors: 'Soil Sensors',
        weatherSensors: 'Weather Sensors',
        irrigationSensors: 'Irrigation Sensors',
        sensorDetails: 'Sensor Details',
        status: 'Status',
        lastUpdated: 'Last updated',
        historicalTrend: 'Historical Trend',
        aiInsights: 'AI-Powered Insights',

        // Blockchain
        cropTracking: 'Crop Tracking',
        secureTracking: 'Secure tracking from farm to market',
        recentBatches: 'Recent Batches',
        batchDetails: 'Batch Details',
        selectBatch: 'Select a batch to view details',
        verifiedOnBlockchain: 'Verified on Blockchain',

        // Landing
        heroTitle: 'Make Smarter Farming Decisions',
        heroSubtitle: 'Stop guessing what to plant. Use data and AI to choose the right crops, avoid oversupply, and increase your profits.',
        startFreeTrial: 'Start Free Trial',
        watchDemo: 'Watch Demo',
        featuresTitle: 'Everything You Need to Succeed',
        featuresSubtitle: 'Simple tools designed for farmers, powered by advanced technology',
        smartCropRec: 'Smart Crop Recommendations',
        smartCropRecDesc: 'Get personalized advice on what to plant based on your soil and local market conditions',
        marketPrice: 'Market Price Predictions',
        marketPriceDesc: 'Know the expected prices before you plant to maximize your profit',
        riskWarnings: 'Risk Warnings',
        riskWarningsDesc: 'Avoid planting crops that might have too much supply and low prices',
        weatherAnalysis: 'Weather Analysis',
        weatherAnalysisDesc: 'Understand how weather will affect your crop yields this season',
        blockchainTracking: 'Blockchain Tracking',
        blockchainTrackingDesc: 'Track your crops from farm to market with secure digital records',
        realtimeMonitoring: 'Real-time Monitoring',
        realtimeMonitoringDesc: 'Monitor soil moisture, temperature, and other important factors',
        ctaTitle: 'Ready to Transform Your Farm?',
        ctaSubtitle: 'Join thousands of farmers who are making better decisions with AgriData Insight',
        getStartedNow: 'Get Started Now',
        footerText: 'Helping farmers make smarter decisions.'
    },
    fr: {
        // Common
        home: 'Accueil',
        login: 'Connexion',
        logout: 'Déconnexion',
        welcome: 'Bienvenue',
        getStarted: 'Commencer',
        blockchainTracker: 'Suivi Blockchain',
        aiAnalytics: 'Analyses IA',
        backToDashboard: 'Retour au Tableau de Bord',
        selectFarm: 'Sélectionner une Ferme',
        noFarmsMessage: 'Aucune ferme trouvée',
        createFarmFirst: 'Veuillez créer une ferme d\'abord en utilisant le formulaire à gauche',
        region: 'Région',
        selectRegion: 'Sélectionner une Région',
        selectedRegion: 'Région Sélectionnée',
        autoDetected: 'Détecté automatiquement',
        aiAdvice: 'Conseils IA',
        allCropsAdvice: 'Conseils pour Toutes les Cultures',
        confidence: 'Niveau de Confiance',
        criticalAdvice: 'Problèmes Critiques',
        warnings: 'Avertissements',
        recommendations: 'Recommandations',
        opportunities: 'Opportunités',
        information: 'Informations',
        action: 'Action Recommandée',
        intendedCrop: 'Culture Prévue',
        optional: 'Optionnel',
        selectIntendedCrop: 'Sélectionnez la Culture que Vous Voulez Planter',
        intendedCropHelp: 'Sélectionnez la culture que vous envisagez de planter. L\'IA l\'analysera et suggérera des alternatives si nécessaire.',
        yourCropAnalysis: 'Analyse de Votre Culture',
        recommended: 'Recommandé',
        notRecommended: 'Non Recommandé',
        alternatives: 'Cultures Alternatives',
        alternativesDescription: 'Basé sur les conditions de votre ferme, ces cultures sont de meilleures alternatives:',
        reason: 'Raison',
        roi: 'ROI',

        // Auth
        welcomeBack: 'Bon Retour',
        signInToAccount: 'Connectez-vous à votre compte AgriData',
        emailAddress: 'Adresse Email',
        password: 'Mot de passe',
        signIn: 'Se Connecter',
        signingIn: 'Connexion...',
        dontHaveAccount: "Vous n'avez pas de compte ?",
        signUp: "S'inscrire",
        backToHome: "Retour à l'accueil",
        createAccount: 'Créer un Compte',
        joinToday: "Rejoignez AgriData Insight aujourd'hui",
        firstName: 'Prénom',
        lastName: 'Nom',
        confirmPassword: 'Confirmer le Mot de Passe',
        creatingAccount: 'Création du compte...',
        alreadyHaveAccount: 'Vous avez déjà un compte ?',

        // Dashboard
        updateFarmDetails: 'Mettre à Jour les Détails de la Ferme',
        farmName: 'Nom de la Ferme',
        location: 'Emplacement',
        size: 'Taille (Hectares)',
        soilType: 'Type de Sol',
        updateAnalysis: 'Mettre à Jour l\'Analyse',
        updating: 'Mise à jour...',
        topRecommendation: 'Meilleure Recommandation',
        recommendedArea: 'Surface Recommandée',
        expectedYield: 'Rendement Attendu',
        expectedRevenue: 'Revenu Estimé',
        ofYourFarm: 'de votre ferme',
        totalHarvest: 'récolte totale',
        estimatedIncome: 'revenu estimé',
        score: 'Score',
        currentContext: 'Contexte Actuel',
        farmId: 'ID de la Ferme',
        analyzingData: 'Analyse des données du sol et du marché...',
        detailedAnalysis: 'Analyse Détaillée',
        crop: 'Culture',
        suitability: 'Aptitude',
        yield: 'Rendement',
        profit: 'Profit',
        risk: 'Risque',
        finalScore: 'Score Final',
        farmUpdatedSuccess: 'Ferme mise à jour avec succès! Recommandations actualisées.',
        soilLoam: 'Limon (Équilibré)',
        soilClay: 'Argile (Lourd)',
        soilSand: 'Sable (Drainant)',
        soilSilt: 'Silt (Fertile)',

        // Analytics
        precisionAnalytics: 'Analyses de Précision',
        realtimeFarmMonitoring: 'Surveillance de Ferme en Temps Réel',
        aiPoweredInsights: 'Informations alimentées par l\'IA à partir de capteurs IoT sur votre ferme',
        soilSensors: 'Capteurs de Sol',
        weatherSensors: 'Capteurs Météo',
        irrigationSensors: 'Capteurs d\'Irrigation',
        sensorDetails: 'Détails du Capteur',
        status: 'Statut',
        lastUpdated: 'Dernière mise à jour',
        historicalTrend: 'Tendance Historique',
        aiInsights: 'Informations IA',

        // Blockchain
        cropTracking: 'Suivi des Cultures',
        secureTracking: 'Suivi sécurisé de la ferme au marché',
        recentBatches: 'Lots Récents',
        batchDetails: 'Détails du Lot',
        selectBatch: 'Sélectionnez un lot pour voir les détails',
        verifiedOnBlockchain: 'Vérifié sur Blockchain',

        // Landing
        heroTitle: 'Prenez des Décisions Agricoles Plus Intelligentes',
        heroSubtitle: 'Arrêtez de deviner quoi planter. Utilisez les données et l\'IA pour choisir les bonnes cultures.',
        startFreeTrial: 'Essai Gratuit',
        watchDemo: 'Voir la Démo',
        featuresTitle: 'Tout ce Dont Vous Avez Besoin',
        featuresSubtitle: 'Outils simples pour les agriculteurs',
        smartCropRec: 'Recommandations Intelligentes',
        smartCropRecDesc: 'Conseils personnalisés sur quoi planter',
        marketPrice: 'Prévisions des Prix',
        marketPriceDesc: 'Connaissez les prix avant de planter',
        riskWarnings: 'Avertissements de Risque',
        riskWarningsDesc: 'Évitez les cultures à risque',
        weatherAnalysis: 'Analyse Météo',
        weatherAnalysisDesc: 'Impact de la météo sur vos rendements',
        blockchainTracking: 'Suivi Blockchain',
        blockchainTrackingDesc: 'Suivez vos cultures',
        realtimeMonitoring: 'Surveillance Temps Réel',
        realtimeMonitoringDesc: 'Surveillez votre ferme',
        ctaTitle: 'Prêt à Transformer Votre Ferme?',
        ctaSubtitle: 'Rejoignez des milliers d\'agriculteurs',
        getStartedNow: 'Commencer Maintenant',
        footerText: 'Aider les agriculteurs.'
    },
    ar: {
        // Common
        home: 'الرئيسية',
        login: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',
        welcome: 'مرحباً',
        getStarted: 'ابدأ الآن',
        blockchainTracker: 'تتبع البلوكشين',
        aiAnalytics: 'تحليلات الذكاء الاصطناعي',
        backToDashboard: 'العودة إلى لوحة التحكم',
        selectFarm: 'اختر المزرعة',
        noFarmsMessage: 'لم يتم العثور على مزارع',
        createFarmFirst: 'يرجى إنشاء مزرعة أولاً باستخدام النموذج على اليسار',
        region: 'المنطقة',
        selectRegion: 'اختر المنطقة',
        selectedRegion: 'المنطقة المختارة',
        autoDetected: 'تم الكشف تلقائياً',
        aiAdvice: 'نصائح الذكاء الاصطناعي',
        allCropsAdvice: 'نصائح لجميع المحاصيل',
        confidence: 'مستوى الثقة',
        criticalAdvice: 'قضايا حرجة',
        warnings: 'تحذيرات',
        recommendations: 'توصيات',
        opportunities: 'فرص',
        information: 'معلومات',
        action: 'الإجراء الموصى به',
        intendedCrop: 'المحصول المقصود',
        optional: 'اختياري',
        selectIntendedCrop: 'اختر المحصول الذي تريد زراعته',
        intendedCropHelp: 'اختر المحصول الذي تفكر في زراعته. سيقوم الذكاء الاصطناعي بتحليله واقتراح بدائل إذا لزم الأمر.',
        yourCropAnalysis: 'تحليل محصولك',
        recommended: 'موصى به',
        notRecommended: 'غير موصى به',
        alternatives: 'محاصيل بديلة',
        alternativesDescription: 'بناءً على ظروف مزرعتك، هذه المحاصيل بدائل أفضل:',
        reason: 'السبب',
        roi: 'العائد على الاستثمار',

        // Auth
        welcomeBack: 'مرحبًا بعودتك',
        signInToAccount: 'سجل الدخول إلى حسابك',
        emailAddress: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        signIn: 'تسجيل الدخول',
        signingIn: 'جاري تسجيل الدخول...',
        dontHaveAccount: 'ليس لديك حساب؟',
        signUp: 'إنشاء حساب',
        backToHome: 'العودة للرئيسية',
        createAccount: 'إنشاء حساب جديد',
        joinToday: 'انضم إلى AgriData Insight اليوم',
        firstName: 'الاسم الأول',
        lastName: 'اسم العائلة',
        confirmPassword: 'تأكيد كلمة المرور',
        creatingAccount: 'جاري إنشاء الحساب...',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',

        // Dashboard
        updateFarmDetails: 'تحديث تفاصيل المزرعة',
        farmName: 'اسم المزرعة',
        location: 'الموقع',
        size: 'الحجم (هكتار)',
        soilType: 'نوع التربة',
        updateAnalysis: 'تحديث التحليل',
        updating: 'جاري التحديث...',
        topRecommendation: 'أفضل توصية',
        recommendedArea: 'المساحة الموصى بها',
        expectedYield: 'الإنتاج المتوقع',
        expectedRevenue: 'الإيرادات المتوقعة',
        ofYourFarm: 'من مزرعتك',
        totalHarvest: 'إجمالي الحصاد',
        estimatedIncome: 'الدخل المقدر',
        score: 'النتيجة',
        currentContext: 'السياق الحالي',
        farmId: 'معرف المزرعة',
        analyzingData: 'جاري تحليل بيانات التربة والسوق...',
        detailedAnalysis: 'تحليل مفصل',
        crop: 'المحصول',
        suitability: 'الملاءمة',
        yield: 'الإنتاج',
        profit: 'الربح',
        risk: 'المخاطر',
        finalScore: 'النتيجة النهائية',
        farmUpdatedSuccess: 'تم تحديث المزرعة بنجاح! تم تحديث التوصيات.',
        soilLoam: 'طمي (متوازن)',
        soilClay: 'طين (ثقيل)',
        soilSand: 'رمل (صرف)',
        soilSilt: 'غرين (خصب)',

        // Analytics
        precisionAnalytics: 'تحليلات الدقة',
        realtimeFarmMonitoring: 'مراقبة المزرعة في الوقت الفعلي',
        aiPoweredInsights: 'رؤى مدعومة بالذكاء الاصطناعي من أجهزة الاستشعار',
        soilSensors: 'مستشعرات التربة',
        weatherSensors: 'مستشعرات الطقس',
        irrigationSensors: 'مستشعرات الري',
        sensorDetails: 'تفاصيل المستشعر',
        status: 'الحالة',
        lastUpdated: 'آخر تحديث',
        historicalTrend: 'الاتجاه التاريخي',
        aiInsights: 'رؤى الذكاء الاصطناعي',

        // Blockchain
        cropTracking: 'تتبع المحاصيل',
        secureTracking: 'تتبع آمن من المزرعة إلى السوق',
        recentBatches: 'الدفعات الأخيرة',
        batchDetails: 'تفاصيل الدفعة',
        selectBatch: 'حدد دفعة لعرض التفاصيل',
        verifiedOnBlockchain: 'تم التحقق على البلوكشين',

        // Landing
        heroTitle: 'اتخذ قرارات زراعية أذكى',
        heroSubtitle: 'توقف عن التخمين. استخدم البيانات والذكاء الاصطناعي.',
        startFreeTrial: 'ابدأ تجربة مجانية',
        watchDemo: 'شاهد العرض',
        featuresTitle: 'كل ما تحتاجه للنجاح',
        featuresSubtitle: 'أدوات بسيطة للمزارعين',
        smartCropRec: 'توصيات ذكية',
        smartCropRecDesc: 'نصائح مخصصة للزراعة',
        marketPrice: 'توقعات الأسعار',
        marketPriceDesc: 'اعرف الأسعار قبل الزراعة',
        riskWarnings: 'تحذيرات المخاطر',
        riskWarningsDesc: 'تجنب المحاصيل عالية المخاطر',
        weatherAnalysis: 'تحليل الطقس',
        weatherAnalysisDesc: 'تأثير الطقس على المحصول',
        blockchainTracking: 'تتبع البلوكشين',
        blockchainTrackingDesc: 'تتبع محاصيلك',
        realtimeMonitoring: 'المراقبة الفورية',
        realtimeMonitoringDesc: 'راقب مزرعتك',
        ctaTitle: 'هل أنت مستعد؟',
        ctaSubtitle: 'انضم إلى آلاف المزارعين',
        getStartedNow: 'ابدأ الآن',
        footerText: 'مساعدة المزارعين.'
    }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en')

    // Crop name translations
    const cropTranslations = {
        en: {
            'Potato': 'Potato',
            'Carrot': 'Carrot',
            'Onion': 'Onion',
            'Tomato': 'Tomato',
            'Wheat': 'Wheat',
            'Barley': 'Barley',
            'Corn': 'Corn',
            'Lettuce': 'Lettuce',
            'Pepper': 'Pepper',
            'Eggplant': 'Eggplant',
            'Cucumber': 'Cucumber',
            'Zucchini': 'Zucchini',
            'Beans': 'Beans',
            'Peas': 'Peas',
            'Cabbage': 'Cabbage',
            'Broccoli': 'Broccoli',
            'Cauliflower': 'Cauliflower',
            'Spinach': 'Spinach',
            'Radish': 'Radish',
            'Beetroot': 'Beetroot',
        },
        fr: {
            'Potato': 'Pomme de terre',
            'Carrot': 'Carotte',
            'Onion': 'Oignon',
            'Tomato': 'Tomate',
            'Wheat': 'Blé',
            'Barley': 'Orge',
            'Corn': 'Maïs',
            'Lettuce': 'Laitue',
            'Pepper': 'Poivron',
            'Eggplant': 'Aubergine',
            'Cucumber': 'Concombre',
            'Zucchini': 'Courgette',
            'Beans': 'Haricots',
            'Peas': 'Pois',
            'Cabbage': 'Chou',
            'Broccoli': 'Brocoli',
            'Cauliflower': 'Chou-fleur',
            'Spinach': 'Épinards',
            'Radish': 'Radis',
            'Beetroot': 'Betterave',
        },
        ar: {
            'Potato': 'بطاطا',
            'Carrot': 'جزر',
            'Onion': 'بصل',
            'Tomato': 'طماطم',
            'Wheat': 'قمح',
            'Barley': 'شعير',
            'Corn': 'ذرة',
            'Lettuce': 'خس',
            'Pepper': 'فلفل',
            'Eggplant': 'باذنجان',
            'Cucumber': 'خيار',
            'Zucchini': 'كوسة',
            'Beans': 'فاصوليا',
            'Peas': 'بازلاء',
            'Cabbage': 'ملفوف',
            'Broccoli': 'بروكلي',
            'Cauliflower': 'قرنبيط',
            'Spinach': 'سبانخ',
            'Radish': 'فجل',
            'Beetroot': 'شمندر',
        }
    }

    const t = (key) => {
        return translations[language][key] || key
    }

    const translateCrop = (cropName) => {
        return cropTranslations[language]?.[cropName] || cropName
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, translateCrop }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
