import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
    en: {
        // Common
        home: 'Home',
        login: 'Login',
        logout: 'Logout',
        welcome: 'Welcome',
        getStarted: 'Get Started',
        blockchainTracker: 'Blockchain Tracker',
        aiAnalytics: 'AI Analytics',
        backToDashboard: 'Back to Dashboard',
        selectFarm: 'Select Farm',
        noFarmsMessage: 'No farms found',
        createFarmFirst: 'Please create a farm first using the form on the left',
        region: 'Region',
        selectRegion: 'Select Region',
        selectedRegion: 'Selected Region',
        autoDetected: 'Auto-detected',
        aiAdvice: 'AI Advice',
        allCropsAdvice: 'Advice for All Crops',
        intendedCrop: 'Intended Crop',
        optional: 'Optional',
        selectIntendedCrop: 'Select Crop You Want to Plant',
        intendedCropHelp: 'Select the crop you are thinking of planting. AI will analyze it and suggest alternatives if needed.',
        yourCropAnalysis: 'Your Crop Analysis',
        recommended: 'Recommended',
        notRecommended: 'Not Recommended',
        alternatives: 'Alternative Crops',
        alternativesDescription: 'Based on your farm conditions, these crops are better alternatives:',
        reason: 'Reason',
        roi: 'ROI',
        confidence: 'Confidence Level',
        criticalAdvice: 'Critical Issues',
        warnings: 'Warnings',
        recommendations: 'Recommendations',
        opportunities: 'Opportunities',
        information: 'Information',
        action: 'Recommended Action',

        // Auth
        welcomeBack: 'Welcome Back',
        signInToAccount: 'Sign in to your AgroVisor account',
        emailAddress: 'Email Address',
        password: 'Password',
        signIn: 'Sign In',
        signingIn: 'Signing in...',
        dontHaveAccount: "Don't have an account?",
        signUp: 'Sign up',
        backToHome: 'Back to home',
        createAccount: 'Create Account',
        joinToday: 'Join AgroVisor today',
        firstName: 'First Name',
        lastName: 'Last Name',
        confirmPassword: 'Confirm Password',
        creatingAccount: 'Creating account...',
        alreadyHaveAccount: 'Already have an account?',
        acceptTerms: 'I accept the',
        termsAndConditions: 'Terms and Conditions',
        termsAndConditionsLink: 'of the Ministry of Agriculture',
        mustAcceptTerms: 'You must accept the terms and conditions to continue',

        // Dashboard
        updateFarmDetails: 'Update Farm Details',
        farmName: 'Farm Name',
        location: 'Location',
        size: 'Size (Hectares)',
        soilType: 'Soil Type',
        updateAnalysis: 'Update Analysis',
        updating: 'Updating...',
        topRecommendation: 'Top Recommendation',
        recommendedArea: 'Recommended Area',
        expectedYield: 'Expected Yield',
        expectedRevenue: 'Expected Revenue',
        ofYourFarm: 'of your farm',
        totalHarvest: 'total harvest',
        estimatedIncome: 'estimated income',
        score: 'Score',
        oversupplyRisk: 'Oversupply Risk',
        pricePredictor: 'Price Predictor',
        expectedPrice: 'Expected Price',
        currentContext: 'Current Context',
        farmId: 'Farm ID',
        analyzingData: 'Analyzing soil and market data...',
        detailedAnalysis: 'Detailed Analysis',
        crop: 'Crop',
        suitability: 'Suitability',
        yield: 'Yield',
        profit: 'Profit',
        risk: 'Risk',
        finalScore: 'Final Score',
        farmUpdatedSuccess: 'Farm updated successfully! Recommendations refreshed.',
        farmSavedSuccessfully: 'Farm saved successfully!',
        farmNameExists: 'A farm with this name already exists. Please choose a different name.',
        farmCreationFailed: 'Failed to create/update farm. Please try again.',
        farmLocation: 'Farm Location',
        selectFarmToViewLocation: 'Select a farm to view its location on the map',
        loadingMap: 'Loading map...',
        mapUnavailable: 'Map Unavailable',
        openInGoogleMaps: 'Open in Google Maps',
        soilLoam: 'Loam (Balanced)',
        soilClay: 'Clay (Heavy)',
        soilSand: 'Sand (Draining)',
        soilSilt: 'Silt (Fertile)',
        // Units
        daPerKg: 'DA/kg',
        tonsPerHa: 'tons/ha',
        tons: 'tons',
        hectares: 'hectares',
        // New features
        pricePredictor: 'Price Predictor',
        expectedPrice: 'Expected Price',
        oversupplyRisk: 'Oversupply Risk',
        saveModelResult: 'Save Model Result',
        saving: 'Saving...',
        savedSuccessfully: 'Saved Successfully!',
        // Charts & Analytics
        charts: 'Charts & Analytics',
        chartsAndAnalysis: 'Charts & Detailed Analysis',
        priceComparison: 'Price Comparison',
        yieldComparison: 'Yield Comparison',
        riskDistribution: 'Oversupply Risk Distribution',
        revenueComparison: 'Expected Revenue Comparison',
        cropDistribution: 'Crop Distribution',
        cropScores: 'Crop Scores',
        rest: 'Rest',
        riskBreakdown: 'Risk Breakdown',
        topCrops: 'Top Crops',
        lowRisk: 'Low Risk',
        mediumRisk: 'Medium Risk',
        highRisk: 'High Risk',
        // Analytics
        precisionAnalytics: 'Precision Analytics',
        realtimeFarmMonitoring: 'Real-Time Farm Monitoring',
        aiPoweredInsights: 'AI-powered insights from IoT sensors across your farm',
        soilSensors: 'Soil Sensors',
        weatherSensors: 'Weather Sensors',
        irrigationSensors: 'Irrigation Sensors',
        sensorDetails: 'Sensor Details',
        status: 'Status',
        lastUpdated: 'Last updated',
        historicalTrend: 'Historical Trend',
        aiInsights: 'AI-Powered Insights',

        // Blockchain
        cropTracking: 'Crop Tracking',
        secureTracking: 'Secure tracking from farm to market',
        recentBatches: 'Recent Batches',
        batchDetails: 'Batch Details',
        selectBatch: 'Select a batch to view details',
        verifiedOnBlockchain: 'Verified on Blockchain',

        // Landing
        heroTitle: 'Make Smarter Farming Decisions',
        heroSubtitle: 'Stop guessing what to plant. Use data and AI to choose the right crops, avoid oversupply, and increase your profits.',
        startFreeTrial: 'Start Free Trial',
        learnMore: 'Learn More',
        featuresTitle: 'Everything You Need to Succeed',
        featuresSubtitle: 'Simple tools designed for farmers, powered by advanced technology',
        smartCropRec: 'Smart Crop Recommendations',
        smartCropRecDesc: 'Get personalized advice on what to plant based on your soil and local market conditions',
        marketPrice: 'Market Price Predictions',
        marketPriceDesc: 'Know the expected prices before you plant to maximize your profit',
        riskWarnings: 'Risk Warnings',
        riskWarningsDesc: 'Avoid planting crops that might have too much supply and low prices',
        weatherAnalysis: 'Weather Analysis',
        weatherAnalysisDesc: 'Understand how weather will affect your crop yields this season',
        blockchainTracking: 'Blockchain Tracking',
        blockchainTrackingDesc: 'Track your crops from farm to market with secure digital records',
        realtimeMonitoring: 'Real-time Monitoring',
        realtimeMonitoringDesc: 'Monitor soil moisture, temperature, and other important factors',
        ctaTitle: 'Ready to Transform Your Farm?',
        ctaSubtitle: 'Join thousands of farmers who are making better decisions with AgroVisor',
        getStartedNow: 'Get Started Now',
        footerText: 'Helping farmers make smarter decisions.',
        
        // Season Simulator
        seasonSimulator: 'Season Simulator',
        currentSeason: 'Current Season',
        selectSeason: 'Select Season',
        seasonalRecommendations: 'Seasonal Recommendations',
        agriculturalCalendar: 'Agricultural Calendar',
        suggestedCrops: 'Suggested Crops',
        seasonalProjections: 'Seasonal Projections',
        spring: 'Spring',
        summer: 'Summer',
        autumn: 'Autumn',
        winter: 'Winter',
        springRec1: 'Start preparing soil for spring planting. Ideal time for tomatoes and peppers.',
        springRec2: 'Monitor soil moisture and temperature for optimal germination.',
        springRec3: 'Begin planting warm-season crops as temperatures rise.',
        summerRec1: 'Increase irrigation frequency due to high temperatures.',
        summerRec2: 'Harvest early crops and prepare for second planting cycle.',
        summerRec3: 'Protect crops from heat stress with proper shading.',
        autumnRec1: 'Plant winter crops like wheat and barley.',
        autumnRec2: 'Prepare for harvest season and storage facilities.',
        autumnRec3: 'Monitor weather for early frost warnings.',
        winterRec1: 'Focus on greenhouse crops and protected cultivation.',
        winterRec2: 'Plan next season\'s crops and order seeds.',
        winterRec3: 'Maintain soil health with cover crops.',
        projection1: 'Optimal planting window for this season\'s recommended crops.',
        projection2: 'Expected weather conditions favor high-yield potential.',
        projection3: 'Market prices projected to be favorable for seasonal crops.',
        january: 'January',
        february: 'February',
        march: 'March',
        april: 'April',
        may: 'May',
        june: 'June',
        july: 'July',
        august: 'August',
        september: 'September',
        october: 'October',
        november: 'November',
        december: 'December'
    },
    fr: {
        // Common
        home: 'Accueil',
        login: 'Connexion',
        logout: 'Déconnexion',
        welcome: 'Bienvenue',
        getStarted: 'Commencer',
        blockchainTracker: 'Suivi Blockchain',
        aiAnalytics: 'Analyses IA',
        backToDashboard: 'Retour au Tableau de Bord',
        selectFarm: 'Sélectionner une Ferme',
        noFarmsMessage: 'Aucune ferme trouvée',
        createFarmFirst: 'Veuillez créer une ferme d\'abord en utilisant le formulaire à gauche',
        region: 'Région',
        selectRegion: 'Sélectionner une Région',
        selectedRegion: 'Région Sélectionnée',
        autoDetected: 'Détecté automatiquement',
        aiAdvice: 'Conseils IA',
        allCropsAdvice: 'Conseils pour Toutes les Cultures',
        confidence: 'Niveau de Confiance',
        criticalAdvice: 'Problèmes Critiques',
        warnings: 'Avertissements',
        recommendations: 'Recommandations',
        opportunities: 'Opportunités',
        information: 'Informations',
        action: 'Action Recommandée',
        intendedCrop: 'Culture Prévue',
        optional: 'Optionnel',
        selectIntendedCrop: 'Sélectionnez la Culture que Vous Voulez Planter',
        intendedCropHelp: 'Sélectionnez la culture que vous envisagez de planter. L\'IA l\'analysera et suggérera des alternatives si nécessaire.',
        yourCropAnalysis: 'Analyse de Votre Culture',
        recommended: 'Recommandé',
        notRecommended: 'Non Recommandé',
        alternatives: 'Cultures Alternatives',
        alternativesDescription: 'Basé sur les conditions de votre ferme, ces cultures sont de meilleures alternatives:',
        reason: 'Raison',
        roi: 'ROI',

        // Auth
        welcomeBack: 'Bon Retour',
        signInToAccount: 'Connectez-vous à votre compte AgroVisor',
        emailAddress: 'Adresse Email',
        password: 'Mot de passe',
        signIn: 'Se Connecter',
        signingIn: 'Connexion...',
        dontHaveAccount: "Vous n'avez pas de compte ?",
        signUp: "S'inscrire",
        backToHome: "Retour à l'accueil",
        createAccount: 'Créer un Compte',
        joinToday: "Rejoignez AgroVisor aujourd'hui",
        firstName: 'Prénom',
        lastName: 'Nom',
        confirmPassword: 'Confirmer le Mot de Passe',
        creatingAccount: 'Création du compte...',
        alreadyHaveAccount: 'Vous avez déjà un compte ?',
        acceptTerms: 'J\'accepte les',
        termsAndConditions: 'Conditions Générales',
        termsAndConditionsLink: 'du Ministère de l\'Agriculture',
        mustAcceptTerms: 'Vous devez accepter les conditions générales pour continuer',

        // Dashboard
        updateFarmDetails: 'Mettre à Jour les Détails de la Ferme',
        farmName: 'Nom de la Ferme',
        location: 'Emplacement',
        size: 'Taille (Hectares)',
        soilType: 'Type de Sol',
        updateAnalysis: 'Mettre à Jour l\'Analyse',
        updating: 'Mise à jour...',
        topRecommendation: 'Meilleure Recommandation',
        recommendedArea: 'Surface Recommandée',
        expectedYield: 'Rendement Attendu',
        expectedRevenue: 'Revenu Estimé',
        ofYourFarm: 'de votre ferme',
        totalHarvest: 'récolte totale',
        estimatedIncome: 'revenu estimé',
        score: 'Score',
        oversupplyRisk: 'Risque de Suroffre',
        pricePredictor: 'Prédicteur de Prix',
        expectedPrice: 'Prix Attendu',
        currentContext: 'Contexte Actuel',
        farmId: 'ID de la Ferme',
        analyzingData: 'Analyse des données du sol et du marché...',
        detailedAnalysis: 'Analyse Détaillée',
        crop: 'Culture',
        suitability: 'Aptitude',
        yield: 'Rendement',
        profit: 'Profit',
        risk: 'Risque',
        finalScore: 'Score Final',
        farmUpdatedSuccess: 'Ferme mise à jour avec succès! Recommandations actualisées.',
        farmSavedSuccessfully: 'Ferme enregistrée avec succès!',
        farmNameExists: 'Une ferme avec ce nom existe déjà. Veuillez choisir un nom différent.',
        farmCreationFailed: 'Échec de la création/mise à jour de la ferme. Veuillez réessayer.',
        farmLocation: 'Localisation de la Ferme',
        selectFarmToViewLocation: 'Sélectionnez une ferme pour voir sa localisation sur la carte',
        loadingMap: 'Chargement de la carte...',
        mapUnavailable: 'Carte Indisponible',
        openInGoogleMaps: 'Ouvrir dans Google Maps',
        soilLoam: 'Limon (Équilibré)',
        soilClay: 'Argile (Lourd)',
        soilSand: 'Sable (Drainant)',
        soilSilt: 'Silt (Fertile)',
        // Units
        daPerKg: 'DA/kg',
        tonsPerHa: 'tonnes/ha',
        tons: 'tonnes',
        hectares: 'hectares',
        // New features
        pricePredictor: 'Prédicteur de Prix',
        expectedPrice: 'Prix Attendu',
        oversupplyRisk: 'Risque de Suroffre',
        saveModelResult: 'Enregistrer le Résultat du Modèle',
        saving: 'Enregistrement...',
        savedSuccessfully: 'Enregistré avec Succès!',
        // Charts & Analytics
        charts: 'Graphiques et Analyses',
        chartsAndAnalysis: 'Graphiques et Analyse Détaillée',
        priceComparison: 'Comparaison des Prix',
        yieldComparison: 'Comparaison des Rendements',
        riskDistribution: 'Distribution du Risque de Sursaturation',
        revenueComparison: 'Comparaison des Revenus Attendus',
        cropDistribution: 'Distribution des Cultures',
        cropScores: 'Scores des Cultures',
        rest: 'Autres',
        riskBreakdown: 'Répartition des Risques',
        topCrops: 'Meilleures Cultures',
        lowRisk: 'Risque Faible',
        mediumRisk: 'Risque Moyen',
        highRisk: 'Risque Élevé',
        // Analytics
        precisionAnalytics: 'Analyses de Précision',
        realtimeFarmMonitoring: 'Surveillance de Ferme en Temps Réel',
        aiPoweredInsights: 'Informations alimentées par l\'IA à partir de capteurs IoT sur votre ferme',
        soilSensors: 'Capteurs de Sol',
        weatherSensors: 'Capteurs Météo',
        irrigationSensors: 'Capteurs d\'Irrigation',
        sensorDetails: 'Détails du Capteur',
        status: 'Statut',
        lastUpdated: 'Dernière mise à jour',
        historicalTrend: 'Tendance Historique',
        aiInsights: 'Informations IA',

        // Blockchain
        cropTracking: 'Suivi des Cultures',
        secureTracking: 'Suivi sécurisé de la ferme au marché',
        recentBatches: 'Lots Récents',
        batchDetails: 'Détails du Lot',
        selectBatch: 'Sélectionnez un lot pour voir les détails',
        verifiedOnBlockchain: 'Vérifié sur Blockchain',

        // Landing
        heroTitle: 'Prenez des Décisions Agricoles Plus Intelligentes',
        heroSubtitle: 'Arrêtez de deviner quoi planter. Utilisez les données et l\'IA pour choisir les bonnes cultures.',
        startFreeTrial: 'Essai Gratuit',
        learnMore: 'En savoir plus',
        featuresTitle: 'Tout ce Dont Vous Avez Besoin',
        featuresSubtitle: 'Outils simples pour les agriculteurs',
        smartCropRec: 'Recommandations Intelligentes',
        smartCropRecDesc: 'Conseils personnalisés sur quoi planter',
        marketPrice: 'Prévisions des Prix',
        marketPriceDesc: 'Connaissez les prix avant de planter',
        riskWarnings: 'Avertissements de Risque',
        riskWarningsDesc: 'Évitez les cultures à risque',
        weatherAnalysis: 'Analyse Météo',
        weatherAnalysisDesc: 'Impact de la météo sur vos rendements',
        blockchainTracking: 'Suivi Blockchain',
        blockchainTrackingDesc: 'Suivez vos cultures',
        realtimeMonitoring: 'Surveillance Temps Réel',
        realtimeMonitoringDesc: 'Surveillez votre ferme',
        ctaTitle: 'Prêt à Transformer Votre Ferme?',
        ctaSubtitle: 'Rejoignez des milliers d\'agriculteurs',
        getStartedNow: 'Commencer Maintenant',
        footerText: 'Aider les agriculteurs.',
        
        // Season Simulator
        seasonSimulator: 'Simulateur de Saisons',
        currentSeason: 'Saison Actuelle',
        selectSeason: 'Sélectionner une Saison',
        seasonalRecommendations: 'Recommandations Saisonnières',
        agriculturalCalendar: 'Calendrier Agricole',
        suggestedCrops: 'Cultures Suggérées',
        seasonalProjections: 'Projections Saisonnières',
        spring: 'Printemps',
        summer: 'Été',
        autumn: 'Automne',
        winter: 'Hiver',
        springRec1: 'Commencez à préparer le sol pour les plantations de printemps. Moment idéal pour les tomates et poivrons.',
        springRec2: 'Surveillez l\'humidité et la température du sol pour une germination optimale.',
        springRec3: 'Commencez à planter les cultures de saison chaude avec la montée des températures.',
        summerRec1: 'Augmentez la fréquence d\'irrigation en raison des températures élevées.',
        summerRec2: 'Récoltez les cultures précoces et préparez le deuxième cycle de plantation.',
        summerRec3: 'Protégez les cultures du stress thermique avec un ombrage approprié.',
        autumnRec1: 'Plantez les cultures d\'hiver comme le blé et l\'orge.',
        autumnRec2: 'Préparez-vous pour la saison des récoltes et les installations de stockage.',
        autumnRec3: 'Surveillez la météo pour les avertissements de gel précoce.',
        winterRec1: 'Concentrez-vous sur les cultures en serre et la culture protégée.',
        winterRec2: 'Planifiez les cultures de la prochaine saison et commandez les graines.',
        winterRec3: 'Maintenez la santé du sol avec des cultures de couverture.',
        projection1: 'Fenêtre de plantation optimale pour les cultures recommandées de cette saison.',
        projection2: 'Les conditions météorologiques attendues favorisent un potentiel de rendement élevé.',
        projection3: 'Les prix du marché devraient être favorables aux cultures saisonnières.',
        january: 'Janvier',
        february: 'Février',
        march: 'Mars',
        april: 'Avril',
        may: 'Mai',
        june: 'Juin',
        july: 'Juillet',
        august: 'Août',
        september: 'Septembre',
        october: 'Octobre',
        november: 'Novembre',
        december: 'Décembre'
    },
    ar: {
        // Common
        home: 'الرئيسية',
        login: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',
        welcome: 'مرحباً',
        getStarted: 'ابدأ الآن',
        blockchainTracker: 'تتبع البلوكشين',
        aiAnalytics: 'تحليلات الذكاء الاصطناعي',
        backToDashboard: 'العودة إلى لوحة التحكم',
        selectFarm: 'اختر المزرعة',
        noFarmsMessage: 'لم يتم العثور على مزارع',
        createFarmFirst: 'يرجى إنشاء مزرعة أولاً باستخدام النموذج على اليسار',
        region: 'المنطقة',
        selectRegion: 'اختر المنطقة',
        selectedRegion: 'المنطقة المختارة',
        autoDetected: 'تم الكشف تلقائياً',
        aiAdvice: 'نصائح الذكاء الاصطناعي',
        allCropsAdvice: 'نصائح لجميع المحاصيل',
        confidence: 'مستوى الثقة',
        criticalAdvice: 'قضايا حرجة',
        warnings: 'تحذيرات',
        recommendations: 'توصيات',
        opportunities: 'فرص',
        information: 'معلومات',
        action: 'الإجراء الموصى به',
        intendedCrop: 'المحصول المقصود',
        optional: 'اختياري',
        selectIntendedCrop: 'اختر المحصول الذي تريد زراعته',
        intendedCropHelp: 'اختر المحصول الذي تفكر في زراعته. سيقوم الذكاء الاصطناعي بتحليله واقتراح بدائل إذا لزم الأمر.',
        yourCropAnalysis: 'تحليل محصولك',
        recommended: 'موصى به',
        notRecommended: 'غير موصى به',
        alternatives: 'محاصيل بديلة',
        alternativesDescription: 'بناءً على ظروف مزرعتك، هذه المحاصيل بدائل أفضل:',
        reason: 'السبب',
        roi: 'العائد على الاستثمار',

        // Auth
        welcomeBack: 'مرحبًا بعودتك',
        signInToAccount: 'سجل الدخول إلى حسابك',
        emailAddress: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        signIn: 'تسجيل الدخول',
        signingIn: 'جاري تسجيل الدخول...',
        dontHaveAccount: 'ليس لديك حساب؟',
        signUp: 'إنشاء حساب',
        backToHome: 'العودة للرئيسية',
        createAccount: 'إنشاء حساب جديد',
        joinToday: 'انضم إلى AgroVisor اليوم',
        firstName: 'الاسم الأول',
        lastName: 'اسم العائلة',
        confirmPassword: 'تأكيد كلمة المرور',
        creatingAccount: 'جاري إنشاء الحساب...',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',
        acceptTerms: 'أوافق على',
        termsAndConditions: 'الشروط والأحكام',
        termsAndConditionsLink: 'وزارة الفلاحة والتنمية الريفية',
        mustAcceptTerms: 'يجب عليك قبول الشروط والأحكام للمتابعة',

        // Dashboard
        updateFarmDetails: 'تحديث تفاصيل المزرعة',
        farmName: 'اسم المزرعة',
        location: 'الموقع',
        size: 'الحجم (هكتار)',
        soilType: 'نوع التربة',
        updateAnalysis: 'تحديث التحليل',
        updating: 'جاري التحديث...',
        topRecommendation: 'أفضل توصية',
        recommendedArea: 'المساحة الموصى بها',
        expectedYield: 'الإنتاج المتوقع',
        expectedRevenue: 'الإيرادات المتوقعة',
        ofYourFarm: 'من مزرعتك',
        totalHarvest: 'إجمالي الحصاد',
        estimatedIncome: 'الدخل المقدر',
        score: 'النتيجة',
        oversupplyRisk: 'مخاطر الإفراط في العرض',
        pricePredictor: 'منبئ السعر',
        expectedPrice: 'السعر المتوقع',
        currentContext: 'السياق الحالي',
        farmId: 'معرف المزرعة',
        analyzingData: 'جاري تحليل بيانات التربة والسوق...',
        detailedAnalysis: 'تحليل مفصل',
        crop: 'المحصول',
        suitability: 'الملاءمة',
        yield: 'الإنتاج',
        profit: 'الربح',
        risk: 'المخاطر',
        finalScore: 'النتيجة النهائية',
        farmUpdatedSuccess: 'تم تحديث المزرعة بنجاح! تم تحديث التوصيات.',
        farmSavedSuccessfully: 'تم حفظ المزرعة بنجاح!',
        farmNameExists: 'مزرعة بهذا الاسم موجودة بالفعل. يرجى اختيار اسم مختلف.',
        farmCreationFailed: 'فشل في إنشاء/تحديث المزرعة. يرجى المحاولة مرة أخرى.',
        farmLocation: 'موقع المزرعة',
        selectFarmToViewLocation: 'اختر مزرعة لعرض موقعها على الخريطة',
        loadingMap: 'جاري تحميل الخريطة...',
        mapUnavailable: 'الخريطة غير متاحة',
        openInGoogleMaps: 'فتح في خرائط Google',
        soilLoam: 'طمي (متوازن)',
        soilClay: 'طين (ثقيل)',
        soilSand: 'رمل (صرف)',
        soilSilt: 'غرين (خصب)',
        // Units
        daPerKg: 'دج/كجم',
        tonsPerHa: 'طن/هكتار',
        tons: 'طن',
        hectares: 'هكتار',
        // New features
        pricePredictor: 'منبئ السعر',
        expectedPrice: 'السعر المتوقع',
        oversupplyRisk: 'مخاطر الإفراط في العرض',
        saveModelResult: 'حفظ نتيجة النموذج',
        saving: 'جاري الحفظ...',
        savedSuccessfully: 'تم الحفظ بنجاح!',
        // Charts & Analytics
        charts: 'الرسوم البيانية والتحليلات',
        chartsAndAnalysis: 'الرسوم البيانية والتحليل المفصل',
        priceComparison: 'مقارنة الأسعار',
        yieldComparison: 'مقارنة المحاصيل',
        riskDistribution: 'توزيع مخاطر الإفراط في العرض',
        revenueComparison: 'مقارنة الإيرادات المتوقعة',
        cropDistribution: 'توزيع المحاصيل',
        cropScores: 'درجات المحاصيل',
        rest: 'الباقي',
        riskBreakdown: 'توزيع المخاطر',
        topCrops: 'أفضل المحاصيل',
        lowRisk: 'مخاطر منخفضة',
        mediumRisk: 'مخاطر متوسطة',
        highRisk: 'مخاطر عالية',
        // Analytics
        precisionAnalytics: 'تحليلات الدقة',
        realtimeFarmMonitoring: 'مراقبة المزرعة في الوقت الفعلي',
        aiPoweredInsights: 'رؤى مدعومة بالذكاء الاصطناعي من أجهزة الاستشعار',
        soilSensors: 'مستشعرات التربة',
        weatherSensors: 'مستشعرات الطقس',
        irrigationSensors: 'مستشعرات الري',
        sensorDetails: 'تفاصيل المستشعر',
        status: 'الحالة',
        lastUpdated: 'آخر تحديث',
        historicalTrend: 'الاتجاه التاريخي',
        aiInsights: 'رؤى الذكاء الاصطناعي',

        // Blockchain
        cropTracking: 'تتبع المحاصيل',
        secureTracking: 'تتبع آمن من المزرعة إلى السوق',
        recentBatches: 'الدفعات الأخيرة',
        batchDetails: 'تفاصيل الدفعة',
        selectBatch: 'حدد دفعة لعرض التفاصيل',
        verifiedOnBlockchain: 'تم التحقق على البلوكشين',

        // Landing
        heroTitle: 'اتخذ قرارات زراعية أذكى',
        heroSubtitle: 'توقف عن التخمين. استخدم البيانات والذكاء الاصطناعي.',
        startFreeTrial: 'ابدأ تجربة مجانية',
        learnMore: 'اعرف المزيد',
        featuresTitle: 'كل ما تحتاجه للنجاح',
        featuresSubtitle: 'أدوات بسيطة للمزارعين',
        smartCropRec: 'توصيات ذكية',
        smartCropRecDesc: 'نصائح مخصصة للزراعة',
        marketPrice: 'توقعات الأسعار',
        marketPriceDesc: 'اعرف الأسعار قبل الزراعة',
        riskWarnings: 'تحذيرات المخاطر',
        riskWarningsDesc: 'تجنب المحاصيل عالية المخاطر',
        weatherAnalysis: 'تحليل الطقس',
        weatherAnalysisDesc: 'تأثير الطقس على المحصول',
        blockchainTracking: 'تتبع البلوكشين',
        blockchainTrackingDesc: 'تتبع محاصيلك',
        realtimeMonitoring: 'المراقبة الفورية',
        realtimeMonitoringDesc: 'راقب مزرعتك',
        ctaTitle: 'هل أنت مستعد؟',
        ctaSubtitle: 'انضم إلى آلاف المزارعين',
        getStartedNow: 'ابدأ الآن',
        footerText: 'مساعدة المزارعين.',
        
        // Season Simulator
        seasonSimulator: 'محاكي المواسم',
        currentSeason: 'الموسم الحالي',
        selectSeason: 'اختر الموسم',
        seasonalRecommendations: 'التوصيات الموسمية',
        agriculturalCalendar: 'التقويم الزراعي',
        suggestedCrops: 'المحاصيل المقترحة',
        seasonalProjections: 'التوقعات الموسمية',
        spring: 'الربيع',
        summer: 'الصيف',
        autumn: 'الخريف',
        winter: 'الشتاء',
        springRec1: 'ابدأ في تحضير التربة للزراعة الربيعية. الوقت المثالي للطماطم والفلفل.',
        springRec2: 'راقب رطوبة التربة ودرجة الحرارة للحصول على إنبات مثالي.',
        springRec3: 'ابدأ في زراعة المحاصيل الدافئة مع ارتفاع درجات الحرارة.',
        summerRec1: 'زد من تكرار الري بسبب درجات الحرارة المرتفعة.',
        summerRec2: 'احصد المحاصيل المبكرة واستعد لدورة الزراعة الثانية.',
        summerRec3: 'احمِ المحاصيل من الإجهاد الحراري بالظل المناسب.',
        autumnRec1: 'ازرع المحاصيل الشتوية مثل القمح والشعير.',
        autumnRec2: 'استعد لموسم الحصاد ومرافق التخزين.',
        autumnRec3: 'راقب الطقس للتحذيرات من الصقيع المبكر.',
        winterRec1: 'ركز على محاصيل الدفيئة والزراعة المحمية.',
        winterRec2: 'خطط لمحاصيل الموسم القادم واطلب البذور.',
        winterRec3: 'حافظ على صحة التربة بمحاصيل الغطاء.',
        projection1: 'نافذة الزراعة المثلى للمحاصيل الموصى بها لهذا الموسم.',
        projection2: 'الظروف الجوية المتوقعة تفضل إمكانية عالية للإنتاج.',
        projection3: 'من المتوقع أن تكون أسعار السوق مواتية للمحاصيل الموسمية.',
        january: 'يناير',
        february: 'فبراير',
        march: 'مارس',
        april: 'أبريل',
        may: 'مايو',
        june: 'يونيو',
        july: 'يوليو',
        august: 'أغسطس',
        september: 'سبتمبر',
        october: 'أكتوبر',
        november: 'نوفمبر',
        december: 'ديسمبر'
    }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
    // Load language from localStorage or default to 'en'
    const [language, setLanguage] = useState(() => {
        const savedLanguage = localStorage.getItem('preferred_language')
        return savedLanguage || 'en'
    })
    
    // Save language to localStorage whenever it changes
    const updateLanguage = (newLanguage) => {
        setLanguage(newLanguage)
        localStorage.setItem('preferred_language', newLanguage)
    }

    // Crop name translations
    const cropTranslations = {
        en: {
            'Potato': 'Potato',
            'Carrot': 'Carrot',
            'Onion': 'Onion',
            'Tomato': 'Tomato',
            'Wheat': 'Wheat',
            'Barley': 'Barley',
            'Corn': 'Corn',
            'Lettuce': 'Lettuce',
            'Pepper': 'Pepper',
            'Eggplant': 'Eggplant',
            'Cucumber': 'Cucumber',
            'Zucchini': 'Zucchini',
            'Beans': 'Beans',
            'Peas': 'Peas',
            'Cabbage': 'Cabbage',
            'Broccoli': 'Broccoli',
            'Cauliflower': 'Cauliflower',
            'Spinach': 'Spinach',
            'Radish': 'Radish',
            'Beetroot': 'Beetroot',
            'Strawberry': 'Strawberry',
            'Apple': 'Apple',
            'Chickpea': 'Chickpea',
            'Citrus': 'Citrus',
            'Date Palm': 'Date Palm',
            'Dates': 'Dates',
            'Garlic': 'Garlic',
            'Lentils': 'Lentils',
            'Melon': 'Melon',
            'Olive': 'Olive',
            'Peanut': 'Peanut',
            'Rice': 'Rice',
            'Watermelon': 'Watermelon',
        },
        fr: {
            'Potato': 'Pomme de terre',
            'Carrot': 'Carotte',
            'Onion': 'Oignon',
            'Tomato': 'Tomate',
            'Wheat': 'Blé',
            'Barley': 'Orge',
            'Corn': 'Maïs',
            'Lettuce': 'Laitue',
            'Pepper': 'Poivron',
            'Eggplant': 'Aubergine',
            'Cucumber': 'Concombre',
            'Zucchini': 'Courgette',
            'Beans': 'Haricots',
            'Peas': 'Pois',
            'Cabbage': 'Chou',
            'Broccoli': 'Brocoli',
            'Cauliflower': 'Chou-fleur',
            'Spinach': 'Épinards',
            'Radish': 'Radis',
            'Beetroot': 'Betterave',
            'Strawberry': 'Fraise',
            'Apple': 'Pomme',
            'Chickpea': 'Pois chiche',
            'Citrus': 'Agrumes',
            'Date Palm': 'Palmier dattier',
            'Dates': 'Dattes',
            'Garlic': 'Ail',
            'Lentils': 'Lentilles',
            'Melon': 'Melon',
            'Olive': 'Olive',
            'Peanut': 'Cacahuète',
            'Rice': 'Riz',
            'Watermelon': 'Pastèque',
        },
        ar: {
            'Potato': 'بطاطا',
            'Carrot': 'جزر',
            'Onion': 'بصل',
            'Tomato': 'طماطم',
            'Wheat': 'قمح',
            'Barley': 'شعير',
            'Corn': 'ذرة',
            'Lettuce': 'خس',
            'Pepper': 'فلفل',
            'Eggplant': 'باذنجان',
            'Cucumber': 'خيار',
            'Zucchini': 'كوسة',
            'Beans': 'فاصوليا',
            'Peas': 'بازلاء',
            'Cabbage': 'ملفوف',
            'Broccoli': 'بروكلي',
            'Cauliflower': 'قرنبيط',
            'Spinach': 'سبانخ',
            'Radish': 'فجل',
            'Beetroot': 'شمندر',
            'Strawberry': 'فراولة',
            'Apple': 'تفاح',
            'Chickpea': 'حمص',
            'Citrus': 'حمضيات',
            'Date Palm': 'نخيل',
            'Dates': 'تمر',
            'Garlic': 'ثوم',
            'Lentils': 'عدس',
            'Melon': 'شمام',
            'Olive': 'زيتون',
            'Peanut': 'فول سوداني',
            'Rice': 'أرز',
            'Watermelon': 'بطيخ',
        }
    }

    const t = (key) => {
        return translations[language][key] || key
    }

    const translateCrop = (cropName) => {
        return cropTranslations[language]?.[cropName] || cropName
    }

    // Region name translations
    const regionTranslations = {
        en: {
            'Adrar': 'Adrar',
            'Ain Defla': 'Ain Defla',
            'Ain Temouchent': 'Ain Temouchent',
            'Algiers': 'Algiers',
            'Annaba': 'Annaba',
            'Batna': 'Batna',
            'Bechar': 'Bechar',
            'Bejaia': 'Bejaia',
            'Beni Abbes': 'Beni Abbes',
            'Biskra': 'Biskra',
            'Blida': 'Blida',
            'Bordj Badji Mokhtar': 'Bordj Badji Mokhtar',
            'Bordj Bou Arreridj': 'Bordj Bou Arreridj',
            'Bouira': 'Bouira',
            'Boumerdes': 'Boumerdes',
            'Chlef': 'Chlef',
            'Constantine': 'Constantine',
            'Djanet': 'Djanet',
            'Djelfa': 'Djelfa',
            'El Bayadh': 'El Bayadh',
            'El Meniaa': 'El Meniaa',
            'El Oued': 'El Oued',
            'El Tarf': 'El Tarf',
            'Ghardaia': 'Ghardaia',
            'Guelma': 'Guelma',
            'Illizi': 'Illizi',
            'In Guezzam': 'In Guezzam',
            'In Salah': 'In Salah',
            'Jijel': 'Jijel',
            'Khenchela': 'Khenchela',
            'Laghouat': 'Laghouat',
            'Mascara': 'Mascara',
            'Medea': 'Medea',
            'Mila': 'Mila',
            'Mostaganem': 'Mostaganem',
            'Msila': 'Msila',
            'Naama': 'Naama',
            'Oran': 'Oran',
            'Ouargla': 'Ouargla',
            'Ouled Djellal': 'Ouled Djellal',
            'Oum El Bouaghi': 'Oum El Bouaghi',
            'Relizane': 'Relizane',
            'Saida': 'Saida',
            'Setif': 'Setif',
            'Sidi Bel Abbes': 'Sidi Bel Abbes',
            'Skikda': 'Skikda',
            'Souk Ahras': 'Souk Ahras',
            'Tamanrasset': 'Tamanrasset',
            'Tebessa': 'Tebessa',
            'Tiaret': 'Tiaret',
            'Timimoun': 'Timimoun',
            'Tindouf': 'Tindouf',
            'Tipaza': 'Tipaza',
            'Tissemsilt': 'Tissemsilt',
            'Tizi Ouzou': 'Tizi Ouzou',
            'Tlemcen': 'Tlemcen',
            'Touggourt': 'Touggourt',
            'Mitidja': 'Mitidja',
        },
        fr: {
            'Adrar': 'Adrar',
            'Ain Defla': 'Aïn Defla',
            'Ain Temouchent': 'Aïn Témouchent',
            'Algiers': 'Alger',
            'Annaba': 'Annaba',
            'Batna': 'Batna',
            'Bechar': 'Béchar',
            'Bejaia': 'Béjaïa',
            'Beni Abbes': 'Beni Abbès',
            'Biskra': 'Biskra',
            'Blida': 'Blida',
            'Bordj Badji Mokhtar': 'Bordj Badji Mokhtar',
            'Bordj Bou Arreridj': 'Bordj Bou Arreridj',
            'Bouira': 'Bouira',
            'Boumerdes': 'Boumerdès',
            'Chlef': 'Chlef',
            'Constantine': 'Constantine',
            'Djanet': 'Djanet',
            'Djelfa': 'Djelfa',
            'El Bayadh': 'El Bayadh',
            'El Meniaa': 'El Meniaa',
            'El Oued': 'El Oued',
            'El Tarf': 'El Tarf',
            'Ghardaia': 'Ghardaïa',
            'Guelma': 'Guelma',
            'Illizi': 'Illizi',
            'In Guezzam': 'In Guezzam',
            'In Salah': 'In Salah',
            'Jijel': 'Jijel',
            'Khenchela': 'Khenchela',
            'Laghouat': 'Laghouat',
            'Mascara': 'Mascara',
            'Medea': 'Médéa',
            'Mila': 'Mila',
            'Mostaganem': 'Mostaganem',
            'Msila': 'Msila',
            'Naama': 'Naâma',
            'Oran': 'Oran',
            'Ouargla': 'Ouargla',
            'Ouled Djellal': 'Ouled Djellal',
            'Oum El Bouaghi': 'Oum El Bouaghi',
            'Relizane': 'Relizane',
            'Saida': 'Saïda',
            'Setif': 'Sétif',
            'Sidi Bel Abbes': 'Sidi Bel Abbès',
            'Skikda': 'Skikda',
            'Souk Ahras': 'Souk Ahras',
            'Tamanrasset': 'Tamanrasset',
            'Tebessa': 'Tébessa',
            'Tiaret': 'Tiaret',
            'Timimoun': 'Timimoun',
            'Tindouf': 'Tindouf',
            'Tipaza': 'Tipaza',
            'Tissemsilt': 'Tissemsilt',
            'Tizi Ouzou': 'Tizi Ouzou',
            'Tlemcen': 'Tlemcen',
            'Touggourt': 'Touggourt',
            'Mitidja': 'Mitidja',
        },
        ar: {
            'Adrar': 'أدرار',
            'Ain Defla': 'عين الدفلى',
            'Ain Temouchent': 'عين تيموشنت',
            'Algiers': 'الجزائر',
            'Annaba': 'عنابة',
            'Batna': 'باتنة',
            'Bechar': 'بشار',
            'Bejaia': 'بجاية',
            'Beni Abbes': 'بني عباس',
            'Biskra': 'بسكرة',
            'Blida': 'البليدة',
            'Bordj Badji Mokhtar': 'برج باجي مختار',
            'Bordj Bou Arreridj': 'برج بوعريريج',
            'Bouira': 'البويرة',
            'Boumerdes': 'بومرداس',
            'Chlef': 'الشلف',
            'Constantine': 'قسنطينة',
            'Djanet': 'جانت',
            'Djelfa': 'الجلفة',
            'El Bayadh': 'البيض',
            'El Meniaa': 'المنيعة',
            'El Oued': 'الوادي',
            'El Tarf': 'الطارف',
            'Ghardaia': 'غرداية',
            'Guelma': 'قالمة',
            'Illizi': 'إيليزي',
            'In Guezzam': 'عين قزام',
            'In Salah': 'عين صالح',
            'Jijel': 'جيجل',
            'Khenchela': 'خنشلة',
            'Laghouat': 'الأغواط',
            'Mascara': 'معسكر',
            'Medea': 'المدية',
            'Mila': 'ميلة',
            'Mostaganem': 'مستغانم',
            'Msila': 'المسيلة',
            'Naama': 'النعامة',
            'Oran': 'وهران',
            'Ouargla': 'ورقلة',
            'Ouled Djellal': 'أولاد جلال',
            'Oum El Bouaghi': 'أم البواقي',
            'Relizane': 'غليزان',
            'Saida': 'سعيدة',
            'Setif': 'سطيف',
            'Sidi Bel Abbes': 'سيدي بلعباس',
            'Skikda': 'سكيكدة',
            'Souk Ahras': 'سوق أهراس',
            'Tamanrasset': 'تمنراست',
            'Tebessa': 'تبسة',
            'Tiaret': 'تيارت',
            'Timimoun': 'تيميمون',
            'Tindouf': 'تندوف',
            'Tipaza': 'تيبازة',
            'Tissemsilt': 'تيسمسيلت',
            'Tizi Ouzou': 'تيزي وزو',
            'Tlemcen': 'تلمسان',
            'Touggourt': 'تقرت',
            'Mitidja': 'متيدجة',
        }
    }

    const translateRegion = (regionName) => {
        return regionTranslations[language]?.[regionName] || regionName
    }

    // Set document direction and language on mount and when language changes
    useEffect(() => {
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
        document.documentElement.lang = language
    }, [language])

    return (
        <LanguageContext.Provider value={{ language, setLanguage: updateLanguage, t, translateCrop, translateRegion }}>
            {children}
        </LanguageContext.Provider>
    )
}

export const useLanguage = () => {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
